import React, { useState } from 'react';
import {
  Home, Grid, Calendar, Briefcase, User, MapPin, Bell, ChevronRight,
  ArrowLeft, Star, Clock, ShieldCheck, Users, CheckCircle2,
  Lock, CreditCard, ChevronDown, Check, Building, Wrench, Compass,
  Layers, Hammer, Droplets, HardHat, FileText, Calculator, PhoneCall,
  X, AlertCircle, LogOut, Info, Settings, Bookmark, Search, Maximize2,
  UploadCloud, Sparkles, Image as ImageIcon
} from 'lucide-react';

// The 12 screens mapped to exact names from the mockup
const SCREENS = [
  { id: 'splash', label: '1. Splash' },
  { id: 'onboarding', label: '2. Onboarding' },
  { id: 'home', label: '3. Home' },
  { id: 'services', label: '4. Services' },
  { id: 'service_detail', label: '5. Detail' },
  { id: 'slot_picker', label: '6. Date & Patch Upload' },
  { id: 'summary', label: '7. Estimation Sent' },
  { id: 'estimation_review', label: '8. Work Estimation' },
  { id: 'payment', label: '9. Payment' },
  { id: 'confirmation', label: '10. Confirmed & Work Started' },
  { id: 'my_bookings', label: '11. Bookings' },
  { id: 'projects', label: '12. Projects' },
  { id: 'profile', label: '13. Profile' }
];

export default function App() {
  const [currentScreen, setCurrentScreen] = useState('home');
  const [fullscreenMode, setFullscreenMode] = useState(false);
  const [activeTab, setActiveTab] = useState('home');

  // Booking & Patch Work Upload Flow State
  const [selectedDate, setSelectedDate] = useState(16); // Only date, no time!
  const [patchDescription, setPatchDescription] = useState('Cracked plaster and seepage dampness across 12x10 ft wall. Need repair and waterproof sealing.');
  const [uploadedPhotos, setUploadedPhotos] = useState(['/images/patch_damage.svg']);
  const [selectedPaymentMethod, setSelectedPaymentMethod] = useState('upi');
  const [bookingFilter, setBookingFilter] = useState('upcoming');
  const [projectFilter, setProjectFilter] = useState('all');

  // Active Estimation Data (generated by the team after reviewing patch photos)
  const [activeEstimation, setActiveEstimation] = useState({
    quoteNumber: 'EST-2025-4160',
    serviceTitle: 'Civil Construction & Patch Repair',
    estimatedDays: '2 Days Completion',
    warranty: '2 Years Seepage & Crack Guarantee',
    items: [
      { name: 'Surface Chipping & Rebar Anti-Rust Coat', qty: '120 sq. ft.', rate: 25, amount: 3000 },
      { name: 'Polymer Modified Concrete Plaster Filling', qty: '120 sq. ft.', rate: 45, amount: 5400 },
      { name: 'Hydrophobic Waterproof Acrylic Sealant', qty: '2 Coats', rate: 1200, amount: 2400 },
      { name: 'Expert Labor & Debris Cleaning', qty: '1 Job', rate: 1200, amount: 1200 }
    ],
    materialCost: 10800,
    laborCost: 1200,
    gst: 2160,
    totalAmount: 14160
  });

  // Sync bottom navigation tabs
  const navigateToTab = (tab) => {
    setActiveTab(tab);
    if (tab === 'home') setCurrentScreen('home');
    if (tab === 'services') setCurrentScreen('services');
    if (tab === 'bookings') setCurrentScreen('my_bookings');
    if (tab === 'projects') setCurrentScreen('projects');
    if (tab === 'profile') setCurrentScreen('profile');
  };

  const jumpToScreen = (screenId) => {
    setCurrentScreen(screenId);
    if (screenId === 'home') setActiveTab('home');
    if (screenId === 'services') setActiveTab('services');
    if (screenId === 'my_bookings') setActiveTab('bookings');
    if (screenId === 'projects') setActiveTab('projects');
    if (screenId === 'profile') setActiveTab('profile');
  };

  // Handle local image file upload
  const handleFileUpload = (e) => {
    const files = e.target.files;
    if (files && files[0]) {
      const url = URL.createObjectURL(files[0]);
      setUploadedPhotos(prev => [...prev, url]);
    }
  };

  const showBottomNav = ['home', 'services', 'my_bookings', 'projects', 'profile'].includes(currentScreen);

  return (
    <div className="simulator-container">
      {/* Top Demo Toolbar to jump to any screen */}
      <div className="top-showcase-bar">
        <div className="showcase-header">
          <div className="brand-label">
            <span className="gold-text">HP</span> HINDUSTAN PROJECTS <span style={{ opacity: 0.6, fontSize: '11px', fontWeight: '400' }}>(Dynamic Estimation Flow)</span>
          </div>
          <button 
            onClick={() => setFullscreenMode(!fullscreenMode)}
            style={{ background: 'rgba(255,255,255,0.1)', border: 'none', color: '#fff', padding: '4px 8px', borderRadius: '6px', cursor: 'pointer', fontSize: '11px', display: 'flex', alignItems: 'center', gap: '4px' }}
          >
            <Maximize2 size={12} /> {fullscreenMode ? 'Bezel' : 'Full'}
          </button>
        </div>

        {/* Screen Selector Pills */}
        <div className="screen-pills-row">
          {SCREENS.map((s) => (
            <button
              key={s.id}
              className={`screen-pill-btn ${currentScreen === s.id ? 'active' : ''}`}
              onClick={() => jumpToScreen(s.id)}
            >
              {s.label}
            </button>
          ))}
        </div>
      </div>

      {/* Native Mobile Phone Chassis */}
      <div className={`native-phone-wrapper ${fullscreenMode ? 'full-view' : ''}`}>
        
        {/* Status Bar with Dynamic Island */}
        <div className={`phone-status-bar ${['splash'].includes(currentScreen) ? 'white-text' : ''}`}>
          <span>9:41</span>
          <div className="dynamic-island" />
          <div style={{ display: 'flex', gap: '5px', alignItems: 'center' }}>
            <span>5G</span>
            <span>100%</span>
          </div>
        </div>

        {/* Scrollable Screen Content */}
        <div className={`screen-scroll-viewport ${!showBottomNav ? 'no-bottom-nav' : ''}`}>

          {/* ================= 1. SPLASH SCREEN ================= */}
          {currentScreen === 'splash' && (
            <div 
              className="fade-in-slide"
              style={{
                flex: 1,
                minHeight: '790px',
                background: 'linear-gradient(180deg, #071930 0%, #0B2545 40%, #0F172A 100%)',
                color: '#fff',
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'space-between',
                padding: '40px 24px 30px 24px',
                position: 'relative'
              }}
            >
              <div style={{ textAlign: 'center', marginTop: '20px' }}>
                <div style={{ width: '64px', height: '64px', background: 'linear-gradient(135deg, #F59E0B 0%, #D97706 100%)', borderRadius: '16px', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 12px auto', boxShadow: '0 8px 24px rgba(245, 158, 11, 0.35)' }}>
                  <span style={{ fontSize: '26px', fontWeight: '900', color: '#071930', fontFamily: 'Outfit', letterSpacing: '-1px' }}>HP</span>
                </div>
                <h1 style={{ fontSize: '20px', fontWeight: '800', letterSpacing: '1px', fontFamily: 'Outfit', textTransform: 'uppercase' }}>
                  Hindustan Projects
                </h1>
                <div style={{ fontSize: '11px', color: '#F59E0B', fontWeight: '600', letterSpacing: '2px', marginTop: '3px', textTransform: 'uppercase' }}>
                  Build • Design • Execute
                </div>
              </div>

              {/* 3D Architectural Building Render (Local file) */}
              <div style={{ borderRadius: '24px', overflow: 'hidden', height: '360px', position: 'relative', boxShadow: '0 15px 35px rgba(0,0,0,0.6)', border: '1px solid rgba(255,255,255,0.1)' }}>
                <img 
                  src="/images/splash_building.jpg" 
                  alt="Modern Construction"
                  onError={(e) => { e.target.src = '/images/construction_site.svg'; }}
                  style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                />
                <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to top, rgba(7,25,48,0.85) 0%, transparent 55%)' }} />
              </div>

              <div style={{ textAlign: 'center' }}>
                <h2 style={{ fontSize: '15px', fontWeight: '700', fontFamily: 'Outfit', lineHeight: '1.4', marginBottom: '14px' }}>
                  Your Trusted Construction & Engineering Service Partner
                </h2>
                
                <div style={{ width: '120px', height: '4px', background: 'rgba(255,255,255,0.2)', borderRadius: '4px', margin: '0 auto 18px auto', overflow: 'hidden' }}>
                  <div style={{ width: '70%', height: '100%', background: '#F59E0B', borderRadius: '4px' }} />
                </div>

                <button 
                  className="btn-hp-primary"
                  style={{ background: '#F59E0B', color: '#071930', fontWeight: '800' }}
                  onClick={() => setCurrentScreen('onboarding')}
                >
                  Get Started →
                </button>
              </div>
            </div>
          )}

          {/* ================= 2. ONBOARDING SCREEN ================= */}
          {currentScreen === 'onboarding' && (
            <div className="fade-in-slide" style={{ padding: '16px 20px 24px 20px', display: 'flex', flex: 1, flexDirection: 'column', justifyContent: 'space-between', background: '#fff', minHeight: '790px' }}>
              <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
                <button 
                  onClick={() => setCurrentScreen('home')}
                  style={{ background: 'none', border: 'none', fontSize: '13px', fontWeight: '600', color: '#64748B', cursor: 'pointer' }}
                >
                  Skip
                </button>
              </div>

              <div>
                <h1 style={{ fontSize: '24px', fontWeight: '800', color: '#0B2545', fontFamily: 'Outfit', lineHeight: '1.25', marginBottom: '8px' }}>
                  Turn Your Vision<br />Into Reality
                </h1>
                <p style={{ fontSize: '13px', color: '#64748B', lineHeight: '1.5' }}>
                  Complete civil, architectural and engineering services — all in one place.
                </p>
              </div>

              {/* 3D Modern White Villa Render (Local file) */}
              <div style={{ position: 'relative', height: '360px', borderRadius: '24px', overflow: 'hidden', boxShadow: 'var(--shadow-lg)' }}>
                <img 
                  src="/images/hero_villa.jpg" 
                  alt="Modern Luxury Villa"
                  onError={(e) => { e.target.src = '/images/construction_site.svg'; }}
                  style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                />
                <div style={{ position: 'absolute', bottom: '16px', right: '16px', background: '#F59E0B', color: '#071930', padding: '10px 14px', borderRadius: '16px', display: 'flex', alignItems: 'center', gap: '6px', fontWeight: '800', fontSize: '12px', boxShadow: '0 6px 16px rgba(245, 158, 11, 0.4)' }}>
                  <HardHat size={18} /> Verified Experts
                </div>
              </div>

              <div>
                <div style={{ display: 'flex', justifyContent: 'center', gap: '6px', marginBottom: '20px' }}>
                  <div style={{ width: '22px', height: '6px', background: '#0B2545', borderRadius: '4px' }} />
                  <div style={{ width: '6px', height: '6px', background: '#E2E8F0', borderRadius: '50%' }} />
                  <div style={{ width: '6px', height: '6px', background: '#E2E8F0', borderRadius: '50%' }} />
                  <div style={{ width: '6px', height: '6px', background: '#E2E8F0', borderRadius: '50%' }} />
                </div>

                <button 
                  className="btn-hp-primary"
                  onClick={() => setCurrentScreen('home')}
                >
                  Get Started
                </button>
              </div>
            </div>
          )}

          {/* ================= 3. HOME SCREEN ================= */}
          {currentScreen === 'home' && (
            <div className="fade-in-slide">
              {/* Location Bar */}
              <div style={{ padding: '12px 18px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#fff', borderBottom: '1px solid #F1F5F9' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <MapPin size={15} color="#0B2545" />
                  <span style={{ fontSize: '13px', fontWeight: '700', color: '#0B2545' }}>Bhilwara, Rajasthan</span>
                  <ChevronDown size={14} color="#64748B" />
                </div>
                <button style={{ width: '34px', height: '34px', borderRadius: '50%', background: '#F8FAFC', border: '1px solid #E2E8F0', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' }}>
                  <Bell size={16} color="#0B2545" />
                </button>
              </div>

              {/* Brand Header */}
              <div style={{ padding: '14px 18px 8px 18px' }}>
                <h1 style={{ fontSize: '18px', fontWeight: '800', color: '#0B2545', fontFamily: 'Outfit', letterSpacing: '0.5px' }}>
                  HINDUSTAN PROJECTS
                </h1>
                <div style={{ fontSize: '11px', color: '#64748B', fontWeight: '500', marginTop: '2px' }}>
                  Construction &nbsp;|&nbsp; Architecture &nbsp;|&nbsp; Engineering
                </div>
              </div>

              {/* Hero Banner Card */}
              <div style={{ padding: '0 16px', margin: '8px 0 16px 0' }}>
                <div style={{ position: 'relative', height: '170px', borderRadius: '20px', overflow: 'hidden', boxShadow: 'var(--shadow-md)' }}>
                  <img 
                    src="/images/hero_villa.jpg" 
                    alt="Luxury Home"
                    onError={(e) => { e.target.src = '/images/construction_site.svg'; }}
                    style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                  />
                  <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to right, rgba(11,37,69,0.92) 0%, rgba(11,37,69,0.65) 60%, transparent 100%)', padding: '18px', display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
                    <h2 style={{ fontSize: '17px', fontWeight: '800', color: '#fff', fontFamily: 'Outfit', lineHeight: '1.3', maxWidth: '200px' }}>
                      Build Better With Expert Services
                    </h2>
                    <button 
                      onClick={() => setCurrentScreen('service_detail')}
                      style={{ marginTop: '12px', background: '#F59E0B', color: '#071930', border: 'none', padding: '8px 14px', borderRadius: '10px', fontSize: '12px', fontWeight: '700', width: 'fit-content', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px' }}
                    >
                      Book an Appointment →
                    </button>
                  </div>
                </div>
              </div>

              {/* 4 Circular Action Buttons */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '8px', padding: '0 16px 18px 16px' }}>
                <div onClick={() => setCurrentScreen('services')} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '6px', cursor: 'pointer' }}>
                  <div style={{ width: '48px', height: '48px', borderRadius: '16px', background: '#EFF6FF', color: '#1D4ED8', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: 'var(--shadow-sm)' }}>
                    <Grid size={22} />
                  </div>
                  <span style={{ fontSize: '11px', fontWeight: '600', color: '#0B2545', textAlign: 'center' }}>Our Services</span>
                </div>

                <div onClick={() => setCurrentScreen('projects')} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '6px', cursor: 'pointer' }}>
                  <div style={{ width: '48px', height: '48px', borderRadius: '16px', background: '#F3E8FF', color: '#7E22CE', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: 'var(--shadow-sm)' }}>
                    <Building size={22} />
                  </div>
                  <span style={{ fontSize: '11px', fontWeight: '600', color: '#0B2545', textAlign: 'center' }}>Recent Projects</span>
                </div>

                <div onClick={() => setCurrentScreen('slot_picker')} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '6px', cursor: 'pointer' }}>
                  <div style={{ width: '48px', height: '48px', borderRadius: '16px', background: '#FEF3C7', color: '#D97706', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: 'var(--shadow-sm)' }}>
                    <Calculator size={22} />
                  </div>
                  <span style={{ fontSize: '11px', fontWeight: '600', color: '#0B2545', textAlign: 'center' }}>Cost Estimator</span>
                </div>

                <div onClick={() => setCurrentScreen('profile')} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '6px', cursor: 'pointer' }}>
                  <div style={{ width: '48px', height: '48px', borderRadius: '16px', background: '#DCFCE7', color: '#15803D', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: 'var(--shadow-sm)' }}>
                    <PhoneCall size={22} />
                  </div>
                  <span style={{ fontSize: '11px', fontWeight: '600', color: '#0B2545', textAlign: 'center' }}>Contact Us</span>
                </div>
              </div>

              {/* Popular Services Section */}
              <div style={{ padding: '0 16px 8px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '14px', fontWeight: '800', color: '#0B2545', fontFamily: 'Outfit' }}>Popular Services</span>
                <span onClick={() => setCurrentScreen('services')} style={{ fontSize: '12px', fontWeight: '600', color: '#1D4ED8', cursor: 'pointer' }}>View All</span>
              </div>

              {/* Service Card from Mockup */}
              <div style={{ padding: '0 16px 20px 16px' }}>
                <div 
                  onClick={() => setCurrentScreen('service_detail')}
                  style={{ background: '#fff', borderRadius: '16px', padding: '12px', border: '1px solid #E2E8F0', display: 'flex', gap: '12px', alignItems: 'center', cursor: 'pointer', boxShadow: 'var(--shadow-sm)' }}
                >
                  <img 
                    src="/images/construction_site.svg" 
                    alt="Civil Construction"
                    style={{ width: '64px', height: '64px', borderRadius: '12px', objectFit: 'cover' }}
                  />
                  <div style={{ flex: 1 }}>
                    <h3 style={{ fontSize: '14px', fontWeight: '700', color: '#0B2545' }}>Civil Construction</h3>
                    <p style={{ fontSize: '11px', color: '#64748B', marginTop: '2px' }}>
                      Residential, Commercial & Industrial Construction
                    </p>
                  </div>
                  <ChevronRight size={18} color="#94A3B8" />
                </div>
              </div>
            </div>
          )}

          {/* ================= 4. OUR SERVICES SCREEN ================= */}
          {currentScreen === 'services' && (
            <div className="fade-in-slide">
              <div className="subscreen-top-header">
                <button className="back-btn" onClick={() => setCurrentScreen('home')}>
                  <ArrowLeft size={18} />
                </button>
                <div className="subscreen-title">Our Services</div>
                <div style={{ width: '24px' }} />
              </div>

              <div style={{ padding: '14px 16px 10px 16px', position: 'relative' }}>
                <Search size={16} style={{ position: 'absolute', left: '28px', top: '24px', color: '#94A3B8' }} />
                <input 
                  type="text" 
                  placeholder="Search services..."
                  style={{ width: '100%', background: '#fff', border: '1px solid #E2E8F0', borderRadius: '12px', padding: '10px 14px 10px 38px', fontSize: '13px', outline: 'none' }}
                />
              </div>

              <div style={{ padding: '0 16px 20px 16px', display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {[
                  { title: 'Civil Construction', subtitle: 'Residential, Commercial, Industrial', icon: Building, color: '#1D4ED8', bg: '#EFF6FF' },
                  { title: 'Architecture & Planning', subtitle: 'Design, Planning, 2D/3D Drawings', icon: Compass, color: '#7E22CE', bg: '#F3E8FF' },
                  { title: 'Survey & Mapping', subtitle: 'Site Survey, Land Measurement, Mapping', icon: Layers, color: '#D97706', bg: '#FEF3C7' },
                  { title: 'Interior & Exterior Design', subtitle: 'Modern & Functional Spaces', icon: Home, color: '#0D9488', bg: '#CCFBF1' },
                  { title: 'Structural Analysis', subtitle: 'Safety & Strength Analysis', icon: Hammer, color: '#EA580C', bg: '#FFEDD5' },
                  { title: 'Waterproofing & Maintenance', subtitle: 'Waterproofing, Patchwork, Repair', icon: Droplets, color: '#0284C7', bg: '#E0F2FE' },
                  { title: 'Project Management Consultancy', subtitle: 'Planning, Execution, Monitoring', icon: FileText, color: '#4F46E5', bg: '#EEF2FF' },
                  { title: 'Cost Estimation', subtitle: 'Detailed & Accurate Estimation', icon: Calculator, color: '#16A34A', bg: '#DCFCE7' }
                ].map((item, idx) => (
                  <div
                    key={idx}
                    onClick={() => setCurrentScreen('service_detail')}
                    style={{ background: '#fff', border: '1px solid #E2E8F0', borderRadius: '14px', padding: '12px 14px', display: 'flex', alignItems: 'center', gap: '12px', cursor: 'pointer' }}
                  >
                    <div style={{ width: '40px', height: '40px', borderRadius: '10px', background: item.bg, color: item.color, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      <item.icon size={20} />
                    </div>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontSize: '13px', fontWeight: '700', color: '#0B2545' }}>{item.title}</div>
                      <div style={{ fontSize: '11px', color: '#64748B', marginTop: '2px' }}>{item.subtitle}</div>
                    </div>
                    <ChevronRight size={16} color="#94A3B8" />
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* ================= 5. SERVICE DETAIL SCREEN ================= */}
          {currentScreen === 'service_detail' && (
            <div className="fade-in-slide">
              <div className="subscreen-top-header">
                <button className="back-btn" onClick={() => setCurrentScreen('services')}>
                  <ArrowLeft size={18} />
                </button>
                <div className="subscreen-title">Service Detail</div>
                <div style={{ width: '24px' }} />
              </div>

              {/* Hero Image */}
              <div style={{ height: '200px', width: '100%', position: 'relative' }}>
                <img 
                  src="/images/construction_site.svg" 
                  alt="Civil Construction"
                  style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                />
              </div>

              <div style={{ padding: '16px' }}>
                <h1 style={{ fontSize: '18px', fontWeight: '800', color: '#0B2545', fontFamily: 'Outfit' }}>
                  Civil Construction
                </h1>
                <p style={{ fontSize: '12px', color: '#64748B', marginTop: '2px' }}>
                  Residential, Commercial & Industrial Construction
                </p>

                <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginTop: '6px' }}>
                  <Star size={14} color="#F59E0B" fill="#F59E0B" />
                  <span style={{ fontSize: '12px', fontWeight: '700', color: '#0F172A' }}>4.8</span>
                  <span style={{ fontSize: '12px', color: '#64748B' }}>(124 reviews)</span>
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '8px', margin: '16px 0' }}>
                  <div style={{ background: '#F8FAFC', border: '1px solid #E2E8F0', borderRadius: '10px', padding: '10px 4px', textAlign: 'center' }}>
                    <Clock size={16} color="#0B2545" style={{ margin: '0 auto 4px auto' }} />
                    <div style={{ fontSize: '10px', fontWeight: '600', color: '#0F172A' }}>Timely Delivery</div>
                  </div>
                  <div style={{ background: '#F8FAFC', border: '1px solid #E2E8F0', borderRadius: '10px', padding: '10px 4px', textAlign: 'center' }}>
                    <ShieldCheck size={16} color="#0B2545" style={{ margin: '0 auto 4px auto' }} />
                    <div style={{ fontSize: '10px', fontWeight: '600', color: '#0F172A' }}>Quality Work</div>
                  </div>
                  <div style={{ background: '#F8FAFC', border: '1px solid #E2E8F0', borderRadius: '10px', padding: '10px 4px', textAlign: 'center' }}>
                    <Users size={16} color="#0B2545" style={{ margin: '0 auto 4px auto' }} />
                    <div style={{ fontSize: '10px', fontWeight: '600', color: '#0F172A' }}>Expert Team</div>
                  </div>
                </div>

                <h3 style={{ fontSize: '13px', fontWeight: '700', color: '#0B2545', marginBottom: '4px' }}>About Service</h3>
                <p style={{ fontSize: '12px', color: '#475569', lineHeight: '1.5', marginBottom: '14px' }}>
                  We provide end-to-end civil construction & maintenance services. Simply upload photos of the patch work area and select your preferred inspection date — we will calculate the accurate estimation!
                </p>

                <h3 style={{ fontSize: '13px', fontWeight: '700', color: '#0B2545', marginBottom: '8px' }}>Key Services</h3>
                <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '6px', fontSize: '12px', color: '#334155', marginBottom: '24px' }}>
                  <li style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>• Building Construction & Repairs</li>
                  <li style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>• Structural Crack & Plaster Patch Work</li>
                  <li style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>• Water Leakage & Dampness Treatment</li>
                  <li style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>• Renovation, Tiling & Remodeling</li>
                </ul>

                <button 
                  className="btn-hp-primary"
                  onClick={() => setCurrentScreen('slot_picker')}
                >
                  Upload Patch Photos & Book Inspection
                </button>
              </div>
            </div>
          )}

          {/* ================= 6. DATE SELECTION & PATCH WORK UPLOAD (NO TIME!) ================= */}
          {currentScreen === 'slot_picker' && (
            <div className="fade-in-slide">
              <div className="subscreen-top-header">
                <button className="back-btn" onClick={() => setCurrentScreen('service_detail')}>
                  <ArrowLeft size={18} />
                </button>
                <div className="subscreen-title">Date & Patch Work Details</div>
                <div style={{ width: '24px' }} />
              </div>

              <div style={{ padding: '16px' }}>
                {/* Mini Service Card */}
                <div style={{ display: 'flex', gap: '12px', alignItems: 'center', background: '#fff', border: '1px solid #E2E8F0', padding: '10px 12px', borderRadius: '14px', marginBottom: '16px' }}>
                  <img 
                    src="/images/construction_site.svg" 
                    alt="Civil Construction"
                    style={{ width: '48px', height: '48px', borderRadius: '10px', objectFit: 'cover' }}
                  />
                  <div>
                    <h4 style={{ fontSize: '13px', fontWeight: '700', color: '#0B2545' }}>Civil Construction & Repairs</h4>
                    <p style={{ fontSize: '11px', color: '#64748B' }}>Custom Work Estimation Workflow</p>
                  </div>
                </div>

                {/* 1. SELECT DATE ONLY (Time removed per user request) */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                  <span style={{ fontSize: '13px', fontWeight: '700', color: '#0B2545' }}>1. Select Preferred Date</span>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '12px', fontWeight: '700', color: '#0B2545' }}>
                    <span>&lt;</span> Apr 2025 <span>&gt;</span>
                  </div>
                </div>

                <div style={{ background: '#fff', border: '1px solid #E2E8F0', borderRadius: '14px', padding: '12px 8px', marginBottom: '16px' }}>
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', textAlign: 'center', fontSize: '10px', color: '#94A3B8', fontWeight: '600', marginBottom: '8px' }}>
                    <span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span>
                  </div>
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', textAlign: 'center', fontSize: '12px', fontWeight: '600' }}>
                    {[13, 14, 15, 16, 17, 18, 19].map(date => (
                      <div 
                        key={date}
                        onClick={() => setSelectedDate(date)}
                        style={{
                          width: '32px',
                          height: '32px',
                          borderRadius: '50%',
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          margin: '0 auto',
                          cursor: 'pointer',
                          background: selectedDate === date ? '#0B2545' : 'transparent',
                          color: selectedDate === date ? '#fff' : '#0F172A',
                          fontWeight: selectedDate === date ? '700' : '500'
                        }}
                      >
                        {date}
                      </div>
                    ))}
                  </div>
                </div>

                {/* 2. UPLOAD PATCH WORK IMAGES */}
                <div style={{ marginBottom: '14px' }}>
                  <div style={{ fontSize: '13px', fontWeight: '700', color: '#0B2545', marginBottom: '6px' }}>
                    2. Upload Images of Patch Work Area
                  </div>
                  <div style={{ fontSize: '11px', color: '#64748B', marginBottom: '8px' }}>
                    Upload clear photos of the damaged wall, crack, seepage, or repair area.
                  </div>

                  {/* Upload Box */}
                  <label style={{ display: 'block', border: '2px dashed #93C5FD', background: '#EFF6FF', borderRadius: '14px', padding: '16px', textAlign: 'center', cursor: 'pointer' }}>
                    <input 
                      type="file" 
                      accept="image/*" 
                      multiple 
                      onChange={handleFileUpload} 
                      style={{ display: 'none' }} 
                    />
                    <UploadCloud size={26} color="#1D4ED8" style={{ margin: '0 auto 4px auto' }} />
                    <div style={{ fontSize: '12px', fontWeight: '700', color: '#1D4ED8' }}>
                      Tap to Take Photo or Upload Image
                    </div>
                    <div style={{ fontSize: '10px', color: '#64748B' }}>
                      JPG, PNG, Video (Max 5 photos)
                    </div>
                  </label>

                  {/* Photos Preview Grid */}
                  {uploadedPhotos.length > 0 && (
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '8px', marginTop: '10px' }}>
                      {uploadedPhotos.map((imgUrl, idx) => (
                        <div key={idx} style={{ position: 'relative', height: '70px', borderRadius: '10px', overflow: 'hidden', border: '1px solid #CBD5E1' }}>
                          <img src={imgUrl} alt="Patch area" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                          <button 
                            onClick={() => setUploadedPhotos(prev => prev.filter((_, i) => i !== idx))}
                            style={{ position: 'absolute', top: '3px', right: '3px', background: 'rgba(0,0,0,0.6)', border: 'none', color: '#fff', borderRadius: '50%', width: '18px', height: '18px', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' }}
                          >
                            <X size={10} />
                          </button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                {/* 3. DESCRIBE WORK */}
                <div style={{ marginBottom: '20px' }}>
                  <div style={{ fontSize: '12px', fontWeight: '700', color: '#0B2545', marginBottom: '4px' }}>
                    3. Patch Work Description:
                  </div>
                  <textarea
                    rows={2}
                    value={patchDescription}
                    onChange={(e) => setPatchDescription(e.target.value)}
                    style={{ width: '100%', borderRadius: '10px', border: '1px solid #CBD5E1', padding: '8px 10px', fontSize: '12px', outline: 'none' }}
                  />
                </div>

                <button 
                  className="btn-hp-primary"
                  onClick={() => setCurrentScreen('summary')}
                >
                  Send for Work Estimation (₹0 Upfront)
                </button>
              </div>
            </div>
          )}

          {/* ================= 7. SUMMARY: REQUEST SENT FOR ESTIMATION ================= */}
          {currentScreen === 'summary' && (
            <div className="fade-in-slide">
              <div className="subscreen-top-header">
                <button className="back-btn" onClick={() => setCurrentScreen('slot_picker')}>
                  <ArrowLeft size={18} />
                </button>
                <div className="subscreen-title">Request Sent</div>
                <div style={{ width: '24px' }} />
              </div>

              <div style={{ padding: '20px 16px', textAlign: 'center' }}>
                <div style={{ width: '56px', height: '56px', borderRadius: '50%', background: '#FEF3C7', color: '#D97706', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 12px auto' }}>
                  <FileText size={28} />
                </div>

                <h2 style={{ fontSize: '17px', fontWeight: '800', color: '#0B2545' }}>
                  Patch Work Photos Submitted!
                </h2>
                <p style={{ fontSize: '12px', color: '#64748B', marginTop: '4px', marginBottom: '18px' }}>
                  Our technical estimation team is analyzing your photos for <strong>{selectedDate} Apr 2025</strong>. We will send the full estimation shortly.
                </p>

                {/* Attached Details Box */}
                <div style={{ background: '#fff', border: '1px solid #E2E8F0', borderRadius: '16px', padding: '14px', textAlign: 'left', marginBottom: '20px' }}>
                  <div style={{ fontSize: '11px', color: '#94A3B8', fontWeight: '700' }}>SERVICE & DATE</div>
                  <div style={{ fontSize: '13px', fontWeight: '700', color: '#0B2545', margin: '2px 0 10px 0' }}>
                    Civil Construction • {selectedDate} Apr 2025
                  </div>

                  <div style={{ fontSize: '11px', color: '#94A3B8', fontWeight: '700' }}>UPLOADED PATCH WORK PHOTOS</div>
                  <div style={{ display: 'flex', gap: '8px', marginTop: '6px' }}>
                    {uploadedPhotos.map((url, i) => (
                      <img key={i} src={url} alt="Patch" style={{ width: '48px', height: '48px', borderRadius: '8px', objectFit: 'cover', border: '1px solid #CBD5E1' }} />
                    ))}
                  </div>
                </div>

                {/* Instant Simulation Action */}
                <div style={{ background: '#F0FDF4', border: '1.5px dashed #10B981', padding: '14px', borderRadius: '14px', marginBottom: '14px' }}>
                  <div style={{ fontSize: '11px', fontWeight: '700', color: '#047857', marginBottom: '6px' }}>
                    ⚡ ESTIMATOR RESPONSE
                  </div>
                  <button 
                    className="btn-hp-primary"
                    style={{ background: '#10B981' }}
                    onClick={() => setCurrentScreen('estimation_review')}
                  >
                    <CheckCircle2 size={16} /> View Team Estimation
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* ================= 8. ESTIMATION OF WORK (REVIEW ESTIMATION) ================= */}
          {currentScreen === 'estimation_review' && (
            <div className="fade-in-slide">
              <div className="subscreen-top-header">
                <button className="back-btn" onClick={() => setCurrentScreen('summary')}>
                  <ArrowLeft size={18} />
                </button>
                <div className="subscreen-title">Work Estimation</div>
                <div style={{ width: '24px' }} />
              </div>

              <div style={{ padding: '16px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
                  <div>
                    <h3 style={{ fontSize: '16px', fontWeight: '800', color: '#0B2545' }}>
                      Estimation #{activeEstimation.quoteNumber}
                    </h3>
                    <div style={{ fontSize: '11px', color: '#64748B' }}>
                      Based on your uploaded patch photos
                    </div>
                  </div>
                  <span style={{ fontSize: '10px', fontWeight: '700', background: '#ECFDF5', color: '#047857', padding: '4px 8px', borderRadius: '6px' }}>
                    APPROVED QUOTE
                  </span>
                </div>

                {/* Warranty & Timeline Pills */}
                <div style={{ display: 'flex', gap: '8px', marginBottom: '14px' }}>
                  <div style={{ flex: 1, background: '#EFF6FF', border: '1px solid #BFDBFE', padding: '8px', borderRadius: '10px', fontSize: '11px', color: '#1E40AF', fontWeight: '600' }}>
                    🛡️ {activeEstimation.warranty}
                  </div>
                  <div style={{ background: '#F8FAFC', border: '1px solid #E2E8F0', padding: '8px', borderRadius: '10px', fontSize: '11px', color: '#334155', fontWeight: '600' }}>
                    ⏱️ {activeEstimation.estimatedDays}
                  </div>
                </div>

                {/* Itemized Work Breakdown */}
                <div style={{ background: '#fff', border: '1px solid #E2E8F0', borderRadius: '16px', padding: '14px', marginBottom: '16px' }}>
                  <div style={{ fontSize: '11px', fontWeight: '700', color: '#64748B', marginBottom: '8px' }}>
                    ESTIMATED SCOPE OF WORK & MATERIALS:
                  </div>

                  {activeEstimation.items.map((item, idx) => (
                    <div key={idx} style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px dashed #E2E8F0', fontSize: '12px' }}>
                      <div>
                        <div style={{ fontWeight: '600', color: '#0B2545' }}>{item.name}</div>
                        <div style={{ fontSize: '10px', color: '#64748B' }}>{item.qty}</div>
                      </div>
                      <div style={{ fontWeight: '700', color: '#0F172A' }}>₹{item.amount.toLocaleString()}</div>
                    </div>
                  ))}

                  <div style={{ borderTop: '1px solid #E2E8F0', marginTop: '10px', paddingTop: '10px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <div>
                      <div style={{ fontSize: '10px', color: '#64748B', fontWeight: '700' }}>TOTAL WORK ESTIMATION</div>
                      <div style={{ fontSize: '10px', color: '#10B981' }}>Includes all materials, labor & GST</div>
                    </div>
                    <div style={{ fontSize: '18px', fontWeight: '800', color: '#0B2545', fontFamily: 'Outfit' }}>
                      ₹{activeEstimation.totalAmount.toLocaleString()}
                    </div>
                  </div>
                </div>

                <button 
                  className="btn-hp-primary"
                  onClick={() => setCurrentScreen('payment')}
                >
                  Approve Estimation & Proceed to Payment
                </button>
              </div>
            </div>
          )}

          {/* ================= 9. PAYMENT SCREEN ================= */}
          {currentScreen === 'payment' && (
            <div className="fade-in-slide">
              <div className="subscreen-top-header">
                <button className="back-btn" onClick={() => setCurrentScreen('estimation_review')}>
                  <ArrowLeft size={18} />
                </button>
                <div className="subscreen-title">Payment</div>
                <div style={{ width: '24px' }} />
              </div>

              <div style={{ padding: '16px' }}>
                <div style={{ background: '#F8FAFC', border: '1px solid #E2E8F0', borderRadius: '14px', padding: '14px', marginBottom: '18px' }}>
                  <div style={{ fontSize: '11px', color: '#64748B', fontWeight: '600' }}>Total Estimation Amount</div>
                  <div style={{ fontSize: '24px', fontWeight: '800', color: '#0B2545', fontFamily: 'Outfit' }}>
                    ₹{activeEstimation.totalAmount.toLocaleString()}
                  </div>
                </div>

                <div style={{ fontSize: '13px', fontWeight: '700', color: '#0B2545', marginBottom: '10px' }}>
                  Select Payment Method
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', marginBottom: '20px' }}>
                  {[
                    { id: 'upi', label: 'UPI (Google Pay, PhonePe, Paytm)' },
                    { id: 'card', label: 'Card (Visa, MasterCard, RuPay)' },
                    { id: 'wallet', label: 'Wallet (Paytm, PhonePe)' },
                    { id: 'netbanking', label: 'Net Banking' },
                    { id: 'cod', label: 'Cash / Pay After Work Milestone' }
                  ].map(method => (
                    <div
                      key={method.id}
                      onClick={() => setSelectedPaymentMethod(method.id)}
                      style={{
                        background: '#fff',
                        border: `1.5px solid ${selectedPaymentMethod === method.id ? '#1D4ED8' : '#E2E8F0'}`,
                        borderRadius: '12px',
                        padding: '12px 14px',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        cursor: 'pointer'
                      }}
                    >
                      <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                        <div style={{ width: '18px', height: '18px', borderRadius: '50%', border: `2px solid ${selectedPaymentMethod === method.id ? '#1D4ED8' : '#CBD5E1'}`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                          {selectedPaymentMethod === method.id && (
                            <div style={{ width: '8px', height: '8px', borderRadius: '50%', background: '#1D4ED8' }} />
                          )}
                        </div>
                        <span style={{ fontSize: '12px', fontWeight: '600', color: '#0F172A' }}>{method.label}</span>
                      </div>
                      <ChevronRight size={14} color="#94A3B8" />
                    </div>
                  ))}
                </div>

                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px', fontSize: '11px', color: '#64748B', marginBottom: '20px' }}>
                  <Lock size={12} color="#10B981" />
                  <span>Your payment is secure and encrypted</span>
                </div>

                <button 
                  className="btn-hp-primary"
                  onClick={() => setCurrentScreen('confirmation')}
                >
                  Pay Now & Start Work
                </button>
              </div>
            </div>
          )}

          {/* ================= 10. CONFIRMATION & WORK STARTED ================= */}
          {currentScreen === 'confirmation' && (
            <div className="fade-in-slide" style={{ padding: '24px 20px', textAlign: 'center', flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
              <div style={{ width: '70px', height: '70px', borderRadius: '50%', background: '#ECFDF5', color: '#10B981', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px auto' }}>
                <CheckCircle2 size={42} />
              </div>

              <h1 style={{ fontSize: '20px', fontWeight: '800', color: '#0B2545', fontFamily: 'Outfit' }}>
                Estimation Approved & Work Started!
              </h1>
              <p style={{ fontSize: '12px', color: '#64748B', marginTop: '4px', marginBottom: '20px' }}>
                Your patch work has been scheduled for <strong>{selectedDate} Apr 2025</strong>. Our execution team is assigned!
              </p>

              <div style={{ background: '#F8FAFC', border: '1px solid #E2E8F0', padding: '8px 14px', borderRadius: '10px', fontSize: '12px', fontWeight: '700', color: '#0B2545', width: 'fit-content', margin: '0 auto 18px auto' }}>
                Booking ID: HP20250416001
              </div>

              <div style={{ background: '#fff', border: '1px solid #E2E8F0', borderRadius: '16px', padding: '16px', textAlign: 'left', display: 'flex', flexDirection: 'column', gap: '10px', marginBottom: '24px' }}>
                <div>
                  <div style={{ fontSize: '10px', color: '#94A3B8', fontWeight: '600' }}>SCHEDULED DATE</div>
                  <div style={{ fontSize: '13px', fontWeight: '700', color: '#0B2545' }}>{selectedDate} Apr 2025</div>
                </div>
                <div>
                  <div style={{ fontSize: '10px', color: '#94A3B8', fontWeight: '600' }}>SERVICE & ESTIMATION</div>
                  <div style={{ fontSize: '13px', fontWeight: '700', color: '#0B2545' }}>Civil Construction & Patch Repair • ₹{activeEstimation.totalAmount.toLocaleString()}</div>
                </div>
                <div>
                  <div style={{ fontSize: '10px', color: '#94A3B8', fontWeight: '600' }}>WARRANTY COVERAGE</div>
                  <div style={{ fontSize: '13px', fontWeight: '700', color: '#10B981' }}>2 Years Seepage & Crack Shield</div>
                </div>
              </div>

              <button 
                className="btn-hp-primary"
                style={{ marginBottom: '10px' }}
                onClick={() => setCurrentScreen('my_bookings')}
              >
                Track Work Progress
              </button>

              <button 
                className="btn-hp-secondary"
                onClick={() => setCurrentScreen('home')}
              >
                Back to Home
              </button>
            </div>
          )}

          {/* ================= 11. MY BOOKINGS SCREEN ================= */}
          {currentScreen === 'my_bookings' && (
            <div className="fade-in-slide">
              <div className="subscreen-top-header">
                <button className="back-btn" onClick={() => setCurrentScreen('home')}>
                  <ArrowLeft size={18} />
                </button>
                <div className="subscreen-title">My Bookings</div>
                <div style={{ width: '24px' }} />
              </div>

              <div style={{ padding: '14px 16px 10px 16px', display: 'flex', gap: '8px' }}>
                {['upcoming', 'past', 'cancelled'].map(tab => (
                  <button
                    key={tab}
                    onClick={() => setBookingFilter(tab)}
                    style={{
                      flex: 1,
                      padding: '7px 0',
                      borderRadius: '8px',
                      border: 'none',
                      background: bookingFilter === tab ? '#0B2545' : '#F1F5F9',
                      color: bookingFilter === tab ? '#fff' : '#64748B',
                      fontSize: '12px',
                      fontWeight: '600',
                      cursor: 'pointer',
                      textTransform: 'capitalize'
                    }}
                  >
                    {tab}
                  </button>
                ))}
              </div>

              <div style={{ padding: '8px 16px 20px 16px', display: 'flex', flexDirection: 'column', gap: '12px' }}>
                {/* Active Work Card */}
                <div style={{ background: '#fff', border: '1px solid #E2E8F0', borderRadius: '16px', padding: '14px', boxShadow: 'var(--shadow-sm)' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '8px' }}>
                    <div style={{ display: 'flex', gap: '10px' }}>
                      <img 
                        src="/images/construction_site.svg" 
                        alt="Civil Construction" 
                        style={{ width: '42px', height: '42px', borderRadius: '10px', objectFit: 'cover' }}
                      />
                      <div>
                        <div style={{ fontSize: '13px', fontWeight: '700', color: '#0B2545' }}>Civil Construction & Patch Work</div>
                        <div style={{ fontSize: '11px', color: '#64748B' }}>{selectedDate} Apr 2025 • Work in Progress</div>
                      </div>
                    </div>
                    <span style={{ fontSize: '10px', fontWeight: '700', background: '#ECFDF5', color: '#047857', padding: '3px 8px', borderRadius: '6px' }}>
                      Work Active
                    </span>
                  </div>

                  <div style={{ fontSize: '10px', color: '#94A3B8', marginBottom: '10px' }}>
                    Booking ID: HP20250416001 • Quote #{activeEstimation.quoteNumber}
                  </div>

                  <div style={{ display: 'flex', justifyContent: 'space-between', borderTop: '1px solid #F1F5F9', paddingTop: '10px', fontSize: '11px', fontWeight: '600', color: '#0B2545' }}>
                    <span style={{ cursor: 'pointer' }} onClick={() => setCurrentScreen('estimation_review')}>View Estimation</span>
                    <span style={{ cursor: 'pointer' }}>Track Team</span>
                    <span style={{ color: '#EF4444', cursor: 'pointer' }}>Support</span>
                  </div>
                </div>

                {/* Card 2 */}
                <div style={{ background: '#fff', border: '1px solid #E2E8F0', borderRadius: '16px', padding: '14px', boxShadow: 'var(--shadow-sm)' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '8px' }}>
                    <div style={{ display: 'flex', gap: '10px' }}>
                      <img 
                        src="/images/hero_villa.jpg" 
                        alt="Architectural Design" 
                        onError={(e) => { e.target.src = '/images/construction_site.svg'; }}
                        style={{ width: '42px', height: '42px', borderRadius: '10px', objectFit: 'cover' }}
                      />
                      <div>
                        <div style={{ fontSize: '13px', fontWeight: '700', color: '#0B2545' }}>Architectural Design</div>
                        <div style={{ fontSize: '11px', color: '#64748B' }}>22 Apr 2025 • Site Inspection</div>
                      </div>
                    </div>
                    <span style={{ fontSize: '10px', fontWeight: '700', background: '#EFF6FF', color: '#1D4ED8', padding: '3px 8px', borderRadius: '6px' }}>
                      Upcoming
                    </span>
                  </div>

                  <div style={{ fontSize: '10px', color: '#94A3B8', marginBottom: '10px' }}>
                    Booking ID: HP20250422002
                  </div>

                  <div style={{ display: 'flex', justifyContent: 'space-between', borderTop: '1px solid #F1F5F9', paddingTop: '10px', fontSize: '11px', fontWeight: '600', color: '#0B2545' }}>
                    <span style={{ cursor: 'pointer' }}>View Details</span>
                    <span style={{ cursor: 'pointer' }}>Reschedule</span>
                    <span style={{ color: '#EF4444', cursor: 'pointer' }}>Cancel</span>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* ================= 12. OUR PROJECTS / PORTFOLIO SCREEN ================= */}
          {currentScreen === 'projects' && (
            <div className="fade-in-slide">
              <div className="subscreen-top-header">
                <button className="back-btn" onClick={() => setCurrentScreen('home')}>
                  <ArrowLeft size={18} />
                </button>
                <div className="subscreen-title">Our Projects</div>
                <div style={{ width: '24px' }} />
              </div>

              {/* Filter Chips */}
              <div style={{ padding: '12px 16px 8px 16px', display: 'flex', gap: '8px', overflowX: 'auto' }}>
                {['all', 'residential', 'commercial', 'industrial'].map(filter => (
                  <button
                    key={filter}
                    onClick={() => setProjectFilter(filter)}
                    style={{
                      padding: '6px 14px',
                      borderRadius: '20px',
                      border: 'none',
                      background: projectFilter === filter ? '#0B2545' : '#F1F5F9',
                      color: projectFilter === filter ? '#fff' : '#64748B',
                      fontSize: '11px',
                      fontWeight: '600',
                      cursor: 'pointer',
                      whiteSpace: 'nowrap',
                      textTransform: 'capitalize'
                    }}
                  >
                    {filter === 'all' ? 'All' : filter}
                  </button>
                ))}
              </div>

              {/* Project Cards (All Local Images) */}
              <div style={{ padding: '8px 16px 20px 16px', display: 'flex', flexDirection: 'column', gap: '14px' }}>
                {/* Project 1 */}
                <div style={{ background: '#fff', border: '1px solid #E2E8F0', borderRadius: '16px', overflow: 'hidden', boxShadow: 'var(--shadow-sm)' }}>
                  <div style={{ height: '140px', width: '100%', position: 'relative' }}>
                    <img 
                      src="/images/hero_villa.jpg" 
                      alt="Modern Villa"
                      onError={(e) => { e.target.src = '/images/construction_site.svg'; }}
                      style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                    />
                    <span style={{ position: 'absolute', top: '10px', right: '10px', background: '#EFF6FF', color: '#1D4ED8', fontSize: '10px', fontWeight: '700', padding: '3px 8px', borderRadius: '6px' }}>
                      Residential
                    </span>
                  </div>
                  <div style={{ padding: '12px' }}>
                    <h3 style={{ fontSize: '14px', fontWeight: '700', color: '#0B2545' }}>Modern Residential Villa</h3>
                    <p style={{ fontSize: '11px', color: '#64748B', marginTop: '2px' }}>Bhilwara • 2024</p>
                  </div>
                </div>

                {/* Project 2 */}
                <div style={{ background: '#fff', border: '1px solid #E2E8F0', borderRadius: '16px', overflow: 'hidden', boxShadow: 'var(--shadow-sm)' }}>
                  <div style={{ height: '140px', width: '100%', position: 'relative' }}>
                    <img 
                      src="/images/warehouse.svg" 
                      alt="Warehouse"
                      style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                    />
                    <span style={{ position: 'absolute', top: '10px', right: '10px', background: '#F0FDF4', color: '#15803D', fontSize: '10px', fontWeight: '700', padding: '3px 8px', borderRadius: '6px' }}>
                      Industrial
                    </span>
                  </div>
                  <div style={{ padding: '12px' }}>
                    <h3 style={{ fontSize: '14px', fontWeight: '700', color: '#0B2545' }}>Industrial Warehouse</h3>
                    <p style={{ fontSize: '11px', color: '#64748B', marginTop: '2px' }}>Bhilwara • 2023</p>
                  </div>
                </div>

                {/* Project 3 */}
                <div style={{ background: '#fff', border: '1px solid #E2E8F0', borderRadius: '16px', overflow: 'hidden', boxShadow: 'var(--shadow-sm)' }}>
                  <div style={{ height: '140px', width: '100%', position: 'relative' }}>
                    <img 
                      src="/images/commercial_glass.svg" 
                      alt="Commercial Building"
                      style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                    />
                    <span style={{ position: 'absolute', top: '10px', right: '10px', background: '#FEF3C7', color: '#B45309', fontSize: '10px', fontWeight: '700', padding: '3px 8px', borderRadius: '6px' }}>
                      Commercial
                    </span>
                  </div>
                  <div style={{ padding: '12px' }}>
                    <h3 style={{ fontSize: '14px', fontWeight: '700', color: '#0B2545' }}>Commercial Building</h3>
                    <p style={{ fontSize: '11px', color: '#64748B', marginTop: '2px' }}>Bhilwara • 2024</p>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* ================= 13. PROFILE SCREEN ================= */}
          {currentScreen === 'profile' && (
            <div className="fade-in-slide">
              <div className="subscreen-top-header">
                <button className="back-btn" onClick={() => setCurrentScreen('home')}>
                  <ArrowLeft size={18} />
                </button>
                <div className="subscreen-title">Profile</div>
                <div style={{ width: '24px' }} />
              </div>

              <div style={{ padding: '16px', display: 'flex', alignItems: 'center', gap: '14px', background: '#fff', borderBottom: '1px solid #E2E8F0' }}>
                <div style={{ width: '52px', height: '52px', borderRadius: '50%', background: '#0B2545', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '20px', fontWeight: '800' }}>
                  PK
                </div>
                <div>
                  <h3 style={{ fontSize: '16px', fontWeight: '700', color: '#0B2545' }}>Piyush Kumar</h3>
                  <div style={{ fontSize: '12px', color: '#64748B' }}>piyush@gmail.com</div>
                </div>
              </div>

              <div style={{ padding: '12px 16px 24px 16px', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                {[
                  { label: 'My Bookings', icon: Calendar, action: () => setCurrentScreen('my_bookings') },
                  { label: 'My Addresses', icon: MapPin },
                  { label: 'Payment Methods', icon: CreditCard, action: () => setCurrentScreen('payment') },
                  { label: 'Notifications', icon: Bell },
                  { label: 'Help & Support', icon: PhoneCall },
                  { label: 'About Us', icon: Info },
                  { label: 'Terms & Conditions', icon: FileText },
                  { label: 'Privacy Policy', icon: ShieldCheck },
                  { label: 'Log Out', icon: LogOut, color: '#EF4444' }
                ].map((item, idx) => (
                  <div
                    key={idx}
                    onClick={item.action}
                    style={{
                      background: '#fff',
                      border: '1px solid #F1F5F9',
                      borderRadius: '12px',
                      padding: '12px 14px',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      cursor: 'pointer'
                    }}
                  >
                    <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                      <item.icon size={16} color={item.color || '#0B2545'} />
                      <span style={{ fontSize: '13px', fontWeight: '600', color: item.color || '#0F172A' }}>
                        {item.label}
                      </span>
                    </div>
                    <ChevronRight size={14} color="#94A3B8" />
                  </div>
                ))}
              </div>
            </div>
          )}

        </div>

        {/* 5-Tab Bottom Navigation Bar */}
        {showBottomNav && (
          <div className="phone-bottom-nav">
            <button 
              className={`nav-tab-btn ${activeTab === 'home' ? 'active' : ''}`}
              onClick={() => navigateToTab('home')}
            >
              <Home size={19} className="nav-icon" />
              <span>Home</span>
            </button>

            <button 
              className={`nav-tab-btn ${activeTab === 'services' ? 'active' : ''}`}
              onClick={() => navigateToTab('services')}
            >
              <Grid size={19} className="nav-icon" />
              <span>Services</span>
            </button>

            <button 
              className={`nav-tab-btn ${activeTab === 'bookings' ? 'active' : ''}`}
              onClick={() => navigateToTab('bookings')}
            >
              <Calendar size={19} className="nav-icon" />
              <span>Bookings</span>
            </button>

            <button 
              className={`nav-tab-btn ${activeTab === 'projects' ? 'active' : ''}`}
              onClick={() => navigateToTab('projects')}
            >
              <Briefcase size={19} className="nav-icon" />
              <span>Projects</span>
            </button>

            <button 
              className={`nav-tab-btn ${activeTab === 'profile' ? 'active' : ''}`}
              onClick={() => navigateToTab('profile')}
            >
              <User size={19} className="nav-icon" />
              <span>Profile</span>
            </button>
          </div>
        )}

      </div>
    </div>
  );
}
